fontsize = 17.0
nerdfonts = false

[install]
alacritty = false
amphetamine = false
anki = false
appcleaner = false
bat = false
bottom = false
build_essential = false
chrome = false
cmake = false
conda = false
discord = false
docker = false
etcher = false
fd = false
firefox = false
flatpak = false
folx = false
fzf = false
git = false
gnome_tweaks = false
go = false
iproute2 = false
iterm2 = false
jabref = false
keka = false
kitty = false
lf = false
lsd = false
lulu = false
magnet = false
meld = false
neofetch = false
neovim = false
ninja = false
nmap = false
node = false
nushell = false
perl = false
python = false
ripgrep = false
ruby = false
rust = false
sd = false
seafile = false
shellcheck = false
signal = false
starship = false
sublime = false
texifier = false
tldr = false
tmux = false
transmission = false
tree = false
typora = false
vlc = false
wezterm = false
wget = false
wireshark = false
xld = false
yate = false
zoom = false
zsh = false
