default-scheme = "base16-catppuccin-frappe"
preferred-schemes = [
    # Dark themes
    "base16-catppuccin-frappe",
    "base16-gruvbox-material-dark-medium",
    "base16-tomorrow-night-eighties",
    "base16-gruvbox-dark-soft",
    "base16-decaf",

    # Light themes
    "base16-catppuccin-latte",
    "base16-one-light",
]

[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-wezterm"
themes-dir = "themes/wezterm"
supported-systems = ["base16", "base24"]
# The 'touch' cmd reloads WezTerm config
hook = """
SRC=$HOME/.local/share/tinted-theming/tinty/repos/tinted-wezterm/themes/wezterm
WEZTERM_DIR="$HOME/.config/wezterm"
if [ -d "$SRC" ]; then
    mkdir -p "$WEZTERM_DIR"
    ln -sfn "$SRC" "$WEZTERM_DIR/colors"
    touch -c "$WEZTERM_DIR/wezterm.lua"
fi
"""

[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-alacritty"
themes-dir = "themes/alacritty"
supported-systems = ["base16", "base24"]
hook = """
touch -c $HOME/.config/alacritty/alacritty.toml
"""

[[items]]
path = "https://github.com/tinted-theming/tinted-terminal"
name = "tinted-kitty"
themes-dir = "themes/kitty"
# Reload kitty
hook = "[[ -n \"$KITTY_PID\" ]] && kill -USR1 \"$KITTY_PID\""
supported-systems = ["base16", "base24"]

[[items]]
name = "tinted-shell"
path = "https://github.com/tinted-theming/tinted-shell"
themes-dir = "scripts"
hook = "[ -n \"$ITERM_SESSION_ID\" ] && source \"$TINTY_THEME_FILE_PATH\""
supported-systems = ["base16", "base24"]
